// Remove 'use client' directive

import React from 'react';
import type { Metadata } from 'next';
// Remove unused imports
// import { usePathname } from 'next/navigation'; 
// import Script from 'next/script'; // Import Script component
import './globals.css'; // Убедитесь, что этот файл существует или закомментируйте
import Header from './components/Header';
import Footer from './components/Footer';
// import AnimatedBackground from './components/AnimatedBackground'; // Keep if used elsewhere, remove if not
// import StarryBackground from './components/StarryBackground'; // Removed
// Import the new wrapper component
import LayoutWrapper from './components/LayoutWrapper';
// Import the context provider and the script loader component
import { ScriptProvider } from './context/ScriptContext';
import ScriptLoader from './components/ScriptLoader';

export const metadata: Metadata = {
  title: 'Gear App', // Можете изменить заголовок
  description: 'Generated by create next app', // Можете изменить описание
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Removed pathname logic

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/planet10.png" type="image/png" />
      </head>
      {/* body remains relative for positioning context */}
      <body className="relative bg-black"> 
        {/* Wrap everything that might need the context in the Provider */}
        <ScriptProvider>
          <LayoutWrapper>
            {/* Render StarryBackground logic is now inside LayoutWrapper */}
            <Header />
            <main className="relative">{children}</main>
            <Footer />
          </LayoutWrapper>
          
          {/* Render the script loader component (it's a client component) */}
          <ScriptLoader /> 
        </ScriptProvider>
      </body>
    </html>
  );
} 